org.gradle.jvmargs=-Xmx1536M
android.useAndroidX=true
android.enableJetifier=true
systemProp.javax.net.ssl.trustStore=/Users/rich.elms/Library/Java/JavaVirtualMachines/ms-17.0.15/Contents/Home/lib/security/cacerts
systemProp.javax.net.ssl.trustStorePassword=changeit
systemProp.com.sun.net.ssl.checkRevocation=false
systemProp.sun.security.ssl.allowUnsafeRenegotiation=true
systemProp.sun.security.ssl.allowLegacyHelloMessages=true