agents:
  queue: macos-12-arm

steps:

  - label: ":test_tube: 3.10.0"
    timeout_in_minutes: 10
    env:
      FLUTTER_BIN: "/opt/flutter/3.10.0/bin/flutter"
    commands:
      - make test

  - label: ":lint-roller: 3.10.0"
    timeout_in_minutes: 10
    env:
      FLUTTER_BIN: "/opt/flutter/3.10.0/bin/flutter"
    commands:
      - make lint

  - label: Build Example App 3.10.0
    timeout_in_minutes: 10
    env:
      FLUTTER_BIN: "/opt/flutter/3.10.0/bin/flutter"
    commands:
      - pod repo update
      - make examples/flutter
      # Verify that App.framework's UUID (and therefore our `codeIdentifier`) changes when Dart code is touched
      - dwarfdump --arch=arm64 --uuid examples/flutter/build/ios/iphoneos/Runner.app/Frameworks/App.framework/App | tee uuid_before
      - sed -i '' -e 's/add_your_api_key_here/my_api_key/' examples/flutter/lib/main.dart
      - make examples/flutter
      - dwarfdump --arch=arm64 --uuid examples/flutter/build/ios/iphoneos/Runner.app/Frameworks/App.framework/App | tee uuid_after
      - test "$(cat uuid_before)" != "$(cat uuid_after)"

  #
  # iOS
  #
  - label: Build iOS Test Fixture 3.10.0
    key: "ios-fixture-3-10-0"
    timeout_in_minutes: 20
    env:
      FLUTTER_BIN: "/opt/flutter/3.10.0/bin/flutter"
    commands:
      - pod repo update trunk
      - bundle install
      - features/scripts/generate_fixture.sh
      - features/scripts/build_ios_app.sh
    plugins:
      artifacts#v1.5.0:
        upload:
          from: "eatures/fixtures/mazerunner/build/ios/ipa"
          to: "features/fixtures/app/build/ios/ipa/app-3.10.0.ipa"
  #
  # Android
  #
  - label: Build Android Test Fixture 3.10.0
    key: "android-fixture-3-10-0"
    timeout_in_minutes: 20
    env:
      FLUTTER_BIN: "/opt/flutter/3.10.0/bin/flutter"
    commands:
      - bundle install
      - features/scripts/generate_fixture.sh
      - features/scripts/build_android_app.sh
    plugins:
      artifacts#v1.5.0:
        upload:
          from: "features/fixtures/app/build/app/outputs/flutter-apk/app-release.apk"
          to: "features/fixtures/app/build/app/outputs/flutter-apk/app-release-3.10.0.apk"
